version: '3'

services:
  db:
    container_name: ktor_sample1
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: "ktor_db"
      POSTGRES_USER: "ktor_user"
      POSTGRES_PASSWORD: "ktor_pass"
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  postgres-data: